### ISSUE TITLE
HW1.1.2

### ISSUE THREAD

**Issue by zpcohen** [kingcohn1/stat679work#1]
@cecileane

**Comment by zpcohen** [comment]
Does this issue give you access to my HW or is it just a way of notifying you that my work is up-to-date?

**Comment by cecileane** [comment]
Hi Zach,
Your repository is public, so anyone has view access (you can turn it private anytime if you wish, in which case no one will have view access except for the people you add as collaborator). This issue is just a way to let me know when your work is ready. When it's ready, add a link to the current commit, like [this](https://github.com/kingcohn1/stat679work/commit/1305f04459858444345908166cc4c14234ed2cde). 

You can use markdown style here. some examples below.

# anything after one pound sign is a super big title.

## after 2 pound signs: smaller title

### after 3 pound signs

`code between backticks`

you can "beautify" your readme file by using this syntax. It looks like you used many pounds signs, so many things appear as big titles. To make the pound sign be interpreted as a comment, do **not** put it first on a line. (2 stars for bold)

``` shell
triple backticks for a full block of code
```

Click on the little pencil near the top of this message to "edit" it: you might not have permission to edit my messages, but at least you will see the raw text that I typed (with the 1/2/3 pound signs, backticks etc.)

**Comment by cecileane** [comment]
Hi Zach,

Just for reference, I'm looking at this [commit 5c14ce3a](https://github.com/kingcohn1/stat679work/commit/5c14ce3a532fe4fc5247a55b4de291a9a175c2b0), not tag 1.22, as you told me.

Your normalization files are clean and efficient, that's great. To make them better, indent the blocks between `do` and `done`. Indentation is really important to make your code readable, and it also helps to detect bugs. Also, you could have combined the 2 commands: `cp` and `rm` with a single command: `mv`. In other words, if you replace
`cp timetest${i}_snaq.out timetest0${i}_snaq.out`
by
`mv timetest${i}_snaq.out timetest0${i}_snaq.out`,
then there is no need to remove the original file afterwards.

In your summarizing script, you did intent the lines between `do` and `done`, which is good. It would have been best to indent all lines in the same way: the last line in the block is less indented than the others (`echo "$analysis,$h,$CPU" >> out5.csv`).

Your summarization script assumes that the directory with log files is named `log/`, but it's named `log2/` in your repository. This assumption in your script comes from line 4: `for i in log/*.log;` (instead of `for i in log2/*.log;`). So to make your script work without modifying any of your files, I copied the whole `log2/` directory into a new `log/` directory like this:
`cp -r log2 log`
but then your script gave me errors, and the resulting file had extra lines:

``` shell
(master)$ bash summarizeSNaQres.sh
i=log/*0?_snaq.log
grep: out/*0?_snaq: No such file or directory
grep: timetest01_snaq: No such file or directory
...
grep: timetest09_snaq.out: No such file or directory
h=0
1 ; analysis=*0?_snaq
...
(master)$ cat out5.csv
analysis,Hmax,cputime
*0?_snaq
timetest01_snaq
timetest02_snaq
timetest03_snaq
timetest04_snaq
timetest05_snaq
timetest06_snaq
timetest07_snaq
timetest08_snaq
timetest09_snaq,0
1,
bT1,0,103354
net1_snaq,1,11648
newtry1,1,88579
timetest01_snaq,1,16688
timetest02_snaq,1,37137
timetest03_snaq,1,12630
timetest04_snaq,1,21942
timetest05_snaq,1,23949
timetest06_snaq,1,39287
timetest07_snaq,1,29822
timetest08_snaq,1,51589
timetest09_snaq,1,34831
timetest10_snaq,1,29394
timetest11_snaq,1,67926
timetest12_snaq,1,18935
timetest13_snaq,1,31456
```

I believe that these errors came from an extra, unwanted file named `*0?_snaq.log` in your `log2/` directory. I suggest that you remove it from your repository with `git rm log2/\*0\?_snaq.log` (from `hw1/` as current directory). The extra `\` is to tell the shell that it's a real `*` and a real `?`: they should not be expanded by the shell.
After I remove this file and run your summary script, the output file is great: with 16 lines as expected.
Your output file `out5.csv` does not have any digits after the decimal point. If would be great if you could capture them and print them in the file.

documentation: In your readme file for the `hw1/` folder, you should say where each script should be run from (`hw1/log2` for `normalizelogs.sh`, `hw1/out` for `normalizeout.sh`, and just `hw1` for `summarizeSNaQres.sh`). You should also say what file your summarizing script creates: and not let the collaborator guess that it's `out5.csv`.

A few things with github and markdown: you could finish to edit your `hw1/readme.md` and `hw1/trialNerrorHW1.1.md` files, to make better use of markdown style, so that github will render them nicely.

Keep up the good work!

**Comment by zpcohen** [comment]
Awesome, what a pleasant surprise it is to sit down for the night shift and see the attention you have paid to my work-I really appreciate it! I will follow your advice and comment you (here) when you can expect to see these changes. :+1:

**Comment by zpcohen** [comment]
Good evening! I am pleased to inform you that my hw1.3 exercise is finally finished, with the help of some colleagues. However, I am having issues committing these changes to github. My local directory is clean with my log2-->log, an updated summarize*.sh and a new .csv but these commits have not translated well to my github directory. I'd rather not manually make the changes, have to pull from git...etc. So, I can include the code here and try to figure out the issue asap. Thanks again for your consideration and see you soon.

``` shell
#!/bin/bash
set -e # script terminates if any command exits with non-zero status
set -u # terminates if any variable is unset
set -o pipefail

echo analysis,nRuns,nFail,fabs,frel,xabs,xrel,seed,under3460,under3450,under3440 > HW13.csv
for i in log/*.log;
do
    analysis=$(basename -s ".log" "$i")
    h=$(grep "hmax" $i | head -n1 | grep -o -E "[0-9]")
        CPU=$(grep -E "Elapsed time. [[:digit:]]+" -o out/$analysis.out)
        Nruns=$(egrep -o "BEGIN. [[:digit:]]+" -o $i | cut -f2 -d':' | egrep -o "[[:digit:]]+")
    Nfail=$(sed -n '5p' $i | grep -o -E "proposals = [[:digit:]]+" | grep -o -E "[[:digit:]]+")
    fabs=$(sed -n '3p' $i | cut -f5 -d" " | grep -E -o "[[:digit:]]+.+[[:digit:]]"
    frel=$(sed -n '3p' $i | cut -f4 -d" " | grep -E -o "[[:digit:]]+.+[[:digit:]]+")
        xabs=$(grep -E "xtolAbs=[[:digit:]].+ " -o $i | head -n1 | egrep -o "[[:digit:]]+.[[:digit:]]+")
    xrel=$(grep -E "xtolRel=[[:digit:]].+" -o $i | head -n1 | egrep -o "[[:digit:]]+.[[:digit:]]+") 
    seed=$(grep -E "seed [[:digit:]]+ " -o $i | head -n1 | egrep -o "[[:digit:]]+") 

l=$(sed -nE 's/.*-loglik=([0-9,]+).*/\1/p' $i)
a=0
b=0
c-0
for number in $l 
    do 
     if [ $number -lt 3460 ]
         then
         a=$((a+1))
    fi
    if [ $number -lt 3450 ]
     then
     b=$((b+1))
    fi
    if [ $number -lt 3440 ]
    then
     c=$((c+1))
    fi
done
echo $analysis,$Nruns,$Nfail,$fabs,$frel,$xabs,$xrel,$seed,$a,$b,$c >> HW13.csv

done
```

**Comment by cecileane** [comment]
Hi Zach,
Could you please open a new issue for this exercise 3, to keep things separate from your work and my feedback on exercises 1-2? Once you open a new issue (with updated title to reflect exercise 3), please close this first one. I would be more than happy to help with your github issues. I'm working in Birge (341) today.

**Comment by zpcohen** [comment]
Yes, I'll close the current issue and open a new one asap. I was visiting
Chicago this weekend and will be taking the bus back with a 5pm eta.
Fortunately, there are outlets and wifi on the bus so we can keep the line
of communication open. Thank you again for your kind consideration-I'm
learning so much from this course!
